package main

import (
	"fmt"

	"github.com/codegangsta/martini"
	"github.com/danielfrg/go-web-template/pkg"
	"github.com/martini-contrib/staticbin"
)

func main() {
	fmt.Println("Starting server")

	m := martini.Classic()

	// Serves the "dist" directory's files from binary data.
	// You have to pass the "Asset" function generated by
	// go-bindata (https://github.com/jteeuwen/go-bindata)
	// This "dist" directory is extra the default "public" dir
	m.Use(staticbin.Static("dist", pkg.Asset))

	m.Get("/version", func() string {
		return pkg.Version()
	})

	m.Run()
}
