package main

import (
    "fmt"
    "github.com/codegangsta/martini"
    "github.com/martini-contrib/staticbin"
    "github.com/codegangsta/martini-contrib/render"

    "github.com/danielfrg/go-web-template/pkg"
)


func main() {
    fmt.Println("Starting server")

    m := martini.Classic()

    // Serves the "static" directory's files from binary data.
    // You have to pass the "Asset" function generated by
    // go-bindata (https://github.com/jteeuwen/go-bindata).
    m.Use(staticbin.Static("dist", pkg.Asset))

    // render html templates from templates directory
    m.Use(render.Renderer())

    m.Get("/", func(r render.Render) {
        r.HTML(200, "index", "jeremy")
    })

    m.Get("/version", func() string {
        return pkg.Version()
    })

    m.Run()
}
